#!/usr/bin/env node

const path = require('path');
const { spawnSync } = require('child_process');

const nagProcessPath = path.join(__dirname, 'dist/pomodoro-nag.js');

spawnSync('node', [nagProcessPath], { cwd: __dirname, stdio: ['inherit', 'inSherit', 'inherit'] });
