#!/usr/bin/env node

const path = require('path');
const { spawnSync } = require('child_process');

const processPath = path.join(__dirname, 'dist/pomodoro-intrusive.js');

spawnSync('node', [processPath, ...process.argv.slice(2), '--currentPath', __dirname], { cwd: __dirname, stdio: ['inherit', 'inherit', 'inherit'] });
 
